#!/bin/sh

# ssh variables to yank
SSH_VARIABLES="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

# where to put the output script
GRABSSH_DIR="$GRABSSH_DIR"
if [ -z "$GRABSSH_DIR" ]; then
    echo "Error: \$GRABSSH_DIR is not set!" >&2
    exit 1
fi

# grab each variable name and format it as an export statement
for x in $SSH_VARIABLES; do
    (eval echo $x=\$$x) |
        sed -e '
            s/=/="/
            s/$/"/
            s/^/export /
        '
done 1> $GRABSSH_DIR/fixssh
