#!/usr/bin/env python

import argparse
import ConfigParser
import os
import sys

homedir = os.environ.get("HOME", os.path.expanduser('~'))
workdir = os.environ.get("WORKDIR", os.path.join(homedir, "work"))

def parse_options():
    parser = argparse.ArgumentParser(description="Read work config settings")
    parser.add_argument("setting", action="store", help="The configuration setting")
    options = parser.parse_args()
    options.config_file = os.path.join(workdir, "conf", "settings.ini")
    return options

def main():
    options = parse_options()
    section, setting = options.setting.split('.', 1)
    config = ConfigParser.SafeConfigParser()

    try:
        config.read(options.config_file)
    except ConfigParser.ParsingError as error:
        sys.exit(error)

    if config.has_option(section, setting):
        print config.get(section, setting)
    else:
        sys.exit()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit("Caught user interrupt. Quiting...")
