#!/bin/bash

PROFILE=$(work-config firefox.profile)
if [ -z "$PROFILE" ]; then
    echo "Error: Unable to get setting firefox.profile from work-config"
    exit 1
fi

echo "Using profile: $PROFILE"
exec firefox -no-remote -P $PROFILE
