#!/bin/sh

WORKLIB=${WORKLIB:-$HOME/worklib}

usage()
{
    cat <<EOF
Usage: $0 workname

Initialize a new work directory (workname) under \$WORKLIB.

(Currently \$WORKLIB = $WORKLIB)

EOF
}

create_subdir()
{
    echo "Creating $NEW_WORKLIB_DIR/$1..."
    mkdir -p "$NEW_WORKLIB_DIR/$1"
}

if [ -z "$1" ]; then
    usage >&2
    exit 1
fi

if [ ! -d "$WORKLIB" ]; then
    mkdir -p "$WORKLIB"
    if [ $? -ne 0 ]; then
        echo "Error: Unable to create worklib root: $WORKLIB" >&2
        exit 1
    fi
fi

NEW_WORKLIB_DIR="$WORKLIB/$1"
echo "Creating workdir '$1' as '$NEW_WORKLIB_DIR'"

create_subdir "conf"
create_subdir "docs"
create_subdir "forms"
create_subdir "misc"
create_subdir "software"
create_subdir "software/browser-extensions"
create_subdir "src"
