#!/bin/sh
#
# Build all of the separate zsh setup files into a single zshrc file. This
# aleviates the performance hit during cold-cache startup situations.
#
bash_header="bash/bashrc.header.in"
bash_footer="bash/bashrc.footer.in"
bashrc_outfile="bash/bashrc.symlink"

bash_files()
{
    if [ -f "$bash_header" ]; then
        echo "$bash_header"
    fi

    find bash/ -iname '*.bash' | sort
    find . -iname '*.bash' | grep -v '^./bash/'

    if [ -f "$bash_footer" ]; then
        echo "$bash_footer"
    fi
}

if [ -f "$bashrc_outfile" ]; then
    rm "$bashrc_outfile"
fi

bash_files | while read FILE; do
    echo        >> "$bashrc_outfile"
    cat "$FILE" >> "$bashrc_outfile"
done
